yarnPath: .yarn/releases/yarn-3.2.3.cjs
packageExtensions:
  postcss-loader@*:
    peerDependencies:
      autoprefixer: "*"
      postcss: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
